package bicicletasegibide.entity;
// Generated 15-nov-2019 18:09:33 by Hibernate Tools 3.2.1.GA



/**
 * Gestiones generated by hbm2java
 */
public class Gestiones  implements java.io.Serializable {


     private GestionesId id;
     private Reparaciones reparaciones;
     private Piezas piezas;
     private Proveedores proveedores;
     private Float cantidad;

    public Gestiones() {
    }

	
    public Gestiones(GestionesId id, Reparaciones reparaciones, Piezas piezas, Proveedores proveedores) {
        this.id = id;
        this.reparaciones = reparaciones;
        this.piezas = piezas;
        this.proveedores = proveedores;
    }
    public Gestiones(GestionesId id, Reparaciones reparaciones, Piezas piezas, Proveedores proveedores, Float cantidad) {
       this.id = id;
       this.reparaciones = reparaciones;
       this.piezas = piezas;
       this.proveedores = proveedores;
       this.cantidad = cantidad;
    }
   
    public GestionesId getId() {
        return this.id;
    }
    
    public void setId(GestionesId id) {
        this.id = id;
    }
    public Reparaciones getReparaciones() {
        return this.reparaciones;
    }
    
    public void setReparaciones(Reparaciones reparaciones) {
        this.reparaciones = reparaciones;
    }
    public Piezas getPiezas() {
        return this.piezas;
    }
    
    public void setPiezas(Piezas piezas) {
        this.piezas = piezas;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }




}


