package bicicletasegibide.entity;
// Generated 15-nov-2019 18:09:33 by Hibernate Tools 3.2.1.GA



/**
 * GestionesId generated by hbm2java
 */
public class GestionesId  implements java.io.Serializable {


     private String piezasCodigopieza;
     private String proveedoresCodigoproveedor;
     private String reparacionesCodigoreparacion;

    public GestionesId() {
    }

    public GestionesId(String piezasCodigopieza, String proveedoresCodigoproveedor, String reparacionesCodigoreparacion) {
       this.piezasCodigopieza = piezasCodigopieza;
       this.proveedoresCodigoproveedor = proveedoresCodigoproveedor;
       this.reparacionesCodigoreparacion = reparacionesCodigoreparacion;
    }
   
    public String getPiezasCodigopieza() {
        return this.piezasCodigopieza;
    }
    
    public void setPiezasCodigopieza(String piezasCodigopieza) {
        this.piezasCodigopieza = piezasCodigopieza;
    }
    public String getProveedoresCodigoproveedor() {
        return this.proveedoresCodigoproveedor;
    }
    
    public void setProveedoresCodigoproveedor(String proveedoresCodigoproveedor) {
        this.proveedoresCodigoproveedor = proveedoresCodigoproveedor;
    }
    public String getReparacionesCodigoreparacion() {
        return this.reparacionesCodigoreparacion;
    }
    
    public void setReparacionesCodigoreparacion(String reparacionesCodigoreparacion) {
        this.reparacionesCodigoreparacion = reparacionesCodigoreparacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GestionesId) ) return false;
		 GestionesId castOther = ( GestionesId ) other; 
         
		 return ( (this.getPiezasCodigopieza()==castOther.getPiezasCodigopieza()) || ( this.getPiezasCodigopieza()!=null && castOther.getPiezasCodigopieza()!=null && this.getPiezasCodigopieza().equals(castOther.getPiezasCodigopieza()) ) )
 && ( (this.getProveedoresCodigoproveedor()==castOther.getProveedoresCodigoproveedor()) || ( this.getProveedoresCodigoproveedor()!=null && castOther.getProveedoresCodigoproveedor()!=null && this.getProveedoresCodigoproveedor().equals(castOther.getProveedoresCodigoproveedor()) ) )
 && ( (this.getReparacionesCodigoreparacion()==castOther.getReparacionesCodigoreparacion()) || ( this.getReparacionesCodigoreparacion()!=null && castOther.getReparacionesCodigoreparacion()!=null && this.getReparacionesCodigoreparacion().equals(castOther.getReparacionesCodigoreparacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPiezasCodigopieza() == null ? 0 : this.getPiezasCodigopieza().hashCode() );
         result = 37 * result + ( getProveedoresCodigoproveedor() == null ? 0 : this.getProveedoresCodigoproveedor().hashCode() );
         result = 37 * result + ( getReparacionesCodigoreparacion() == null ? 0 : this.getReparacionesCodigoreparacion().hashCode() );
         return result;
   }   


}


