package bicicletasegibide.entity;
// Generated 15-nov-2019 18:09:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private String codigoproveedor;
     private String nombre;
     private String apellidos;
     private String direccion;
     private Set gestioneses = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(String codigoproveedor, String nombre, String apellidos, String direccion) {
        this.codigoproveedor = codigoproveedor;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.direccion = direccion;
    }
    public Proveedores(String codigoproveedor, String nombre, String apellidos, String direccion, Set gestioneses) {
       this.codigoproveedor = codigoproveedor;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.gestioneses = gestioneses;
    }
   
    public String getCodigoproveedor() {
        return this.codigoproveedor;
    }
    
    public void setCodigoproveedor(String codigoproveedor) {
        this.codigoproveedor = codigoproveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getGestioneses() {
        return this.gestioneses;
    }
    
    public void setGestioneses(Set gestioneses) {
        this.gestioneses = gestioneses;
    }




}


