/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 15-nov-2019, 18:11:29
 */

package vista;

import bicicletasegibide.entity.Piezas;
import bicicletasegibide.entity.Proveedores;
import bicicletasegibide.entity.Reparaciones;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.ModeloTablaPiezas;
import modelo.ModeloTablaProveedores;
import modelo.ModeloTablaReparaciones;

/**
 *
 * @author armas
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();
        
        // atributos arrayList de control
        ArrayList arrayListPiezas = new ArrayList();
        ArrayList arrayListProveedores = new ArrayList();
        ArrayList arrayListReparaciones = new ArrayList();

        // objetos de control
        Piezas pieza = new Piezas();
        Proveedores proveedor = new Proveedores();
        Reparaciones reparacion = new Reparaciones();

        // inicializo los arrayList
        arrayListPiezas = pieza.listarPiezas();
        arrayListProveedores = proveedor.listarProveedores();
        arrayListReparaciones = reparacion.listarReparaciones();

        // inicializo los tablemodels
        this.modeloTablaPiezas = new ModeloTablaPiezas(arrayListPiezas);
        this.modeloTablaProveedores = new ModeloTablaProveedores(arrayListProveedores);
        this.modeloTablaReparaciones = new ModeloTablaReparaciones(arrayListReparaciones);

        // inserto los modelos a las tablas
        this.tablaPiezas.setModel(this.modeloTablaPiezas);
        this.tablaProveedores.setModel(this.modeloTablaProveedores);
        this.tablaReparaciones.setModel(this.modeloTablaReparaciones);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        contenedorPiezas = new javax.swing.JPanel();
        contenedorPiezasControl = new javax.swing.JPanel();
        nuevaButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldCodigoPieza = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldPrecio = new javax.swing.JTextField();
        textFieldDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPiezas = new javax.swing.JTable();
        contenedorPiezasBusquedaAvan = new javax.swing.JPanel();
        jRadioButtonPiezasCodigo = new javax.swing.JRadioButton();
        jRadioButtonPiezasNombre = new javax.swing.JRadioButton();
        jRadioButtonTodasLasPiezas = new javax.swing.JRadioButton();
        textFieldBusquAvanzPiezas = new javax.swing.JTextField();
        buttonBusqAvanzPiezas = new javax.swing.JButton();
        contenedorProveedores = new javax.swing.JPanel();
        contenedorGestionProveedores = new javax.swing.JPanel();
        buttonNuevoProveedor = new javax.swing.JButton();
        buttonEliminarProveedor = new javax.swing.JButton();
        buttonActualizarProveedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldCodigoProveedor = new javax.swing.JTextField();
        textFieldNombreProveedor = new javax.swing.JTextField();
        textFieldApellidos = new javax.swing.JTextField();
        textFieldDireccion = new javax.swing.JTextField();
        contenedorTablaProveedores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        contenedorBusquedaAvProveedores = new javax.swing.JPanel();
        jRadioButtonCodigoProveedores = new javax.swing.JRadioButton();
        jRadioButtonNombreProveedores = new javax.swing.JRadioButton();
        jRadioButtonDireccionProveedores = new javax.swing.JRadioButton();
        jRadioButtonListarProveedores = new javax.swing.JRadioButton();
        textFieldBusqAvanProveedores = new javax.swing.JTextField();
        buttonBusqAvanzProveedores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        contenedorReparaciones = new javax.swing.JPanel();
        contenedorGestionReparaciones = new javax.swing.JPanel();
        buttonNuevaReparacion = new javax.swing.JButton();
        buttonEliminarReparacion = new javax.swing.JButton();
        buttonActualizarReparacion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textFieldCodigoReparacion = new javax.swing.JTextField();
        textFieldNombreReparacion = new javax.swing.JTextField();
        textFieldCiudadReparacion = new javax.swing.JTextField();
        contenedorTablaProveedores1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReparaciones = new javax.swing.JTable();
        contenedorBusquedaAvGestiones = new javax.swing.JPanel();
        jRadioButtonCodigoReparacion = new javax.swing.JRadioButton();
        jRadioButtonNombreReparacion = new javax.swing.JRadioButton();
        jRadioButtonCiudadReparacion = new javax.swing.JRadioButton();
        jRadioButtonListarReparaciones = new javax.swing.JRadioButton();
        jButtonBusqAvanzreparaciones = new javax.swing.JButton();
        textFieldBusqAvanzReparaciones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Gestión Taller Bicicletas");
        setResizable(false);

        contenedorPiezas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        contenedorPiezasControl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Control Piezas"));

        nuevaButton.setText("Nueva");
        nuevaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Código pieza:");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Precio:");

        jLabel4.setText("Descripción:");

        javax.swing.GroupLayout contenedorPiezasControlLayout = new javax.swing.GroupLayout(contenedorPiezasControl);
        contenedorPiezasControl.setLayout(contenedorPiezasControlLayout);
        contenedorPiezasControlLayout.setHorizontalGroup(
            contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPiezasControlLayout.createSequentialGroup()
                .addComponent(nuevaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contenedorPiezasControlLayout.createSequentialGroup()
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCodigoPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {actualizarButton, eliminarButton, nuevaButton});

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldCodigoPieza, textFieldDescripcion, textFieldNombre, textFieldPrecio});

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        contenedorPiezasControlLayout.setVerticalGroup(
            contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorPiezasControlLayout.createSequentialGroup()
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCodigoPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorPiezasControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(actualizarButton)
                    .addComponent(nuevaButton)
                    .addComponent(eliminarButton)))
        );

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {actualizarButton, eliminarButton, nuevaButton});

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textFieldCodigoPieza, textFieldDescripcion, textFieldNombre, textFieldPrecio});

        contenedorPiezasControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        tablaPiezas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaPiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPiezas);

        contenedorPiezasBusquedaAvan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Búsqueda Avanzada"));

        jRadioButtonPiezasCodigo.setText("Por código");

        jRadioButtonPiezasNombre.setText("Por nombre");

        jRadioButtonTodasLasPiezas.setText("Listar piezas");

        buttonBusqAvanzPiezas.setText("Buscar");
        buttonBusqAvanzPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBusqAvanzPiezasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorPiezasBusquedaAvanLayout = new javax.swing.GroupLayout(contenedorPiezasBusquedaAvan);
        contenedorPiezasBusquedaAvan.setLayout(contenedorPiezasBusquedaAvanLayout);
        contenedorPiezasBusquedaAvanLayout.setHorizontalGroup(
            contenedorPiezasBusquedaAvanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPiezasBusquedaAvanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorPiezasBusquedaAvanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorPiezasBusquedaAvanLayout.createSequentialGroup()
                        .addComponent(textFieldBusquAvanzPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(buttonBusqAvanzPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonPiezasCodigo)
                    .addComponent(jRadioButtonPiezasNombre)
                    .addComponent(jRadioButtonTodasLasPiezas))
                .addContainerGap())
        );
        contenedorPiezasBusquedaAvanLayout.setVerticalGroup(
            contenedorPiezasBusquedaAvanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPiezasBusquedaAvanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPiezasCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPiezasNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTodasLasPiezas)
                .addGap(18, 18, 18)
                .addGroup(contenedorPiezasBusquedaAvanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBusquAvanzPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBusqAvanzPiezas))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorPiezasLayout = new javax.swing.GroupLayout(contenedorPiezas);
        contenedorPiezas.setLayout(contenedorPiezasLayout);
        contenedorPiezasLayout.setHorizontalGroup(
            contenedorPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPiezasLayout.createSequentialGroup()
                .addGroup(contenedorPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorPiezasLayout.createSequentialGroup()
                        .addComponent(contenedorPiezasControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contenedorPiezasBusquedaAvan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addContainerGap())
        );
        contenedorPiezasLayout.setVerticalGroup(
            contenedorPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorPiezasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedorPiezasBusquedaAvan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorPiezasControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Piezas", contenedorPiezas);

        contenedorProveedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contenedorGestionProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestión Proveedores"));

        buttonNuevoProveedor.setText("Nuevo");
        buttonNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoProveedorActionPerformed(evt);
            }
        });

        buttonEliminarProveedor.setText("Eliminar");
        buttonEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarProveedorActionPerformed(evt);
            }
        });

        buttonActualizarProveedor.setText("Actualizar");
        buttonActualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarProveedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Código:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Apellidos:");

        jLabel8.setText("Dirección:");

        javax.swing.GroupLayout contenedorGestionProveedoresLayout = new javax.swing.GroupLayout(contenedorGestionProveedores);
        contenedorGestionProveedores.setLayout(contenedorGestionProveedoresLayout);
        contenedorGestionProveedoresLayout.setHorizontalGroup(
            contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorGestionProveedoresLayout.createSequentialGroup()
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorGestionProveedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonNuevoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonActualizarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addGroup(contenedorGestionProveedoresLayout.createSequentialGroup()
                        .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        contenedorGestionProveedoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldApellidos, textFieldCodigoProveedor, textFieldDireccion, textFieldNombreProveedor});

        contenedorGestionProveedoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, jLabel8});

        contenedorGestionProveedoresLayout.setVerticalGroup(
            contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorGestionProveedoresLayout.createSequentialGroup()
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorGestionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuevoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonActualizarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        contenedorGestionProveedoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textFieldApellidos, textFieldCodigoProveedor, textFieldDireccion, textFieldNombreProveedor});

        contenedorGestionProveedoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, jLabel8});

        contenedorTablaProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProveedores);

        javax.swing.GroupLayout contenedorTablaProveedoresLayout = new javax.swing.GroupLayout(contenedorTablaProveedores);
        contenedorTablaProveedores.setLayout(contenedorTablaProveedoresLayout);
        contenedorTablaProveedoresLayout.setHorizontalGroup(
            contenedorTablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorTablaProveedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenedorTablaProveedoresLayout.setVerticalGroup(
            contenedorTablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        contenedorBusquedaAvProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Búsqueda Avanzada"));

        jRadioButtonCodigoProveedores.setText("Por código");

        jRadioButtonNombreProveedores.setText("Por nombre");

        jRadioButtonDireccionProveedores.setText("Por dirección");

        jRadioButtonListarProveedores.setText("Listar proveedores");

        buttonBusqAvanzProveedores.setText("Buscar");
        buttonBusqAvanzProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBusqAvanzProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorBusquedaAvProveedoresLayout = new javax.swing.GroupLayout(contenedorBusquedaAvProveedores);
        contenedorBusquedaAvProveedores.setLayout(contenedorBusquedaAvProveedoresLayout);
        contenedorBusquedaAvProveedoresLayout.setHorizontalGroup(
            contenedorBusquedaAvProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBusquedaAvProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorBusquedaAvProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCodigoProveedores)
                    .addComponent(jRadioButtonNombreProveedores)
                    .addComponent(jRadioButtonDireccionProveedores)
                    .addComponent(jRadioButtonListarProveedores)
                    .addGroup(contenedorBusquedaAvProveedoresLayout.createSequentialGroup()
                        .addComponent(textFieldBusqAvanProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBusqAvanzProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contenedorBusquedaAvProveedoresLayout.setVerticalGroup(
            contenedorBusquedaAvProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBusquedaAvProveedoresLayout.createSequentialGroup()
                .addComponent(jRadioButtonCodigoProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNombreProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDireccionProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonListarProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorBusquedaAvProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBusqAvanProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBusqAvanzProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout contenedorProveedoresLayout = new javax.swing.GroupLayout(contenedorProveedores);
        contenedorProveedores.setLayout(contenedorProveedoresLayout);
        contenedorProveedoresLayout.setHorizontalGroup(
            contenedorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorProveedoresLayout.createSequentialGroup()
                .addGroup(contenedorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorProveedoresLayout.createSequentialGroup()
                        .addComponent(contenedorGestionProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contenedorBusquedaAvProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(contenedorTablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        contenedorProveedoresLayout.setVerticalGroup(
            contenedorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorProveedoresLayout.createSequentialGroup()
                .addComponent(contenedorTablaProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(contenedorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedorBusquedaAvProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorGestionProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", contenedorProveedores);

        contenedorReparaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contenedorGestionReparaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestión Reparaciones"));

        buttonNuevaReparacion.setText("Nueva");
        buttonNuevaReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevaReparacionActionPerformed(evt);
            }
        });

        buttonEliminarReparacion.setText("Eliminar");
        buttonEliminarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarReparacionActionPerformed(evt);
            }
        });

        buttonActualizarReparacion.setText("Actualizar");
        buttonActualizarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarReparacionActionPerformed(evt);
            }
        });

        jLabel9.setText("Código:");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Ciudad:");

        javax.swing.GroupLayout contenedorGestionReparacionesLayout = new javax.swing.GroupLayout(contenedorGestionReparaciones);
        contenedorGestionReparaciones.setLayout(contenedorGestionReparacionesLayout);
        contenedorGestionReparacionesLayout.setHorizontalGroup(
            contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorGestionReparacionesLayout.createSequentialGroup()
                .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorGestionReparacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonNuevaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEliminarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonActualizarReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(contenedorGestionReparacionesLayout.createSequentialGroup()
                        .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNombreReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(textFieldCiudadReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(textFieldCodigoReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))
                .addContainerGap())
        );
        contenedorGestionReparacionesLayout.setVerticalGroup(
            contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorGestionReparacionesLayout.createSequentialGroup()
                .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldCodigoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textFieldNombreReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textFieldCiudadReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(contenedorGestionReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNuevaReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEliminarReparacion)
                    .addComponent(buttonActualizarReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        contenedorTablaProveedores1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaReparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tablaReparaciones);

        javax.swing.GroupLayout contenedorTablaProveedores1Layout = new javax.swing.GroupLayout(contenedorTablaProveedores1);
        contenedorTablaProveedores1.setLayout(contenedorTablaProveedores1Layout);
        contenedorTablaProveedores1Layout.setHorizontalGroup(
            contenedorTablaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        contenedorTablaProveedores1Layout.setVerticalGroup(
            contenedorTablaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        contenedorBusquedaAvGestiones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Búsqueda Avanzada"));

        jRadioButtonCodigoReparacion.setText("Por código");

        jRadioButtonNombreReparacion.setText("Por nombre");

        jRadioButtonCiudadReparacion.setText("Por ciudad");

        jRadioButtonListarReparaciones.setText("Listar reparaciones");

        jButtonBusqAvanzreparaciones.setText("Buscar");
        jButtonBusqAvanzreparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusqAvanzreparacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorBusquedaAvGestionesLayout = new javax.swing.GroupLayout(contenedorBusquedaAvGestiones);
        contenedorBusquedaAvGestiones.setLayout(contenedorBusquedaAvGestionesLayout);
        contenedorBusquedaAvGestionesLayout.setHorizontalGroup(
            contenedorBusquedaAvGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBusquedaAvGestionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorBusquedaAvGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCodigoReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jRadioButtonNombreReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jRadioButtonCiudadReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(contenedorBusquedaAvGestionesLayout.createSequentialGroup()
                        .addComponent(jRadioButtonListarReparaciones)
                        .addContainerGap(257, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorBusquedaAvGestionesLayout.createSequentialGroup()
                        .addComponent(textFieldBusqAvanzReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBusqAvanzreparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        contenedorBusquedaAvGestionesLayout.setVerticalGroup(
            contenedorBusquedaAvGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBusquedaAvGestionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCodigoReparacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNombreReparacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCiudadReparacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonListarReparaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorBusquedaAvGestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBusqAvanzreparaciones)
                    .addComponent(textFieldBusqAvanzReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorReparacionesLayout = new javax.swing.GroupLayout(contenedorReparaciones);
        contenedorReparaciones.setLayout(contenedorReparacionesLayout);
        contenedorReparacionesLayout.setHorizontalGroup(
            contenedorReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorTablaProveedores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorReparacionesLayout.createSequentialGroup()
                .addComponent(contenedorGestionReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(contenedorBusquedaAvGestiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contenedorReparacionesLayout.setVerticalGroup(
            contenedorReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorReparacionesLayout.createSequentialGroup()
                .addComponent(contenedorTablaProveedores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(contenedorReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedorGestionReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorBusquedaAvGestiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedorReparaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedorReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reparaciones", jPanel3);

        javax.swing.GroupLayout contenedorPrincipalLayout = new javax.swing.GroupLayout(contenedorPrincipal);
        contenedorPrincipal.setLayout(contenedorPrincipalLayout);
        contenedorPrincipalLayout.setHorizontalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorPrincipalLayout.setVerticalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-787)/2, (screenSize.height-472)/2, 787, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:

        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaPiezas.getSelectedRow();

        // compruebo que el usuario haya elegido alguna fila
        if (rowSeleccionada == -1) {

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA");

        } else {

            // obtengo los datos de la fila
            String cod = this.tablaPiezas.getModel().getValueAt(rowSeleccionada, 0).toString();
            String n = this.tablaPiezas.getModel().getValueAt(rowSeleccionada, 1).toString();
            String p = this.tablaPiezas.getModel().getValueAt(rowSeleccionada, 2).toString();
            String d = this.tablaPiezas.getModel().getValueAt(rowSeleccionada, 3).toString();

            // elimino del modelo la row
            this.modeloTablaPiezas.eliminarPieza(rowSeleccionada);

            // creo el objeto
            Piezas pieza = new Piezas(cod, n, Float.parseFloat(p), d);

            // borro de la bd la pieza
            pieza.borrarPieza(pieza);

        }


    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        // TODO add your handling code here:

        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaPiezas.getSelectedRow();

        // compruebo que una celda esté seleccionada
        if(rowSeleccionada>=0){

            //obtengo los valores de la fila que se está editando
            String cod = this.tablaPiezas.getValueAt(rowSeleccionada, 0).toString();
            String n = this.tablaPiezas.getValueAt(rowSeleccionada, 1).toString();
            String p = this.tablaPiezas.getValueAt(rowSeleccionada, 2).toString();
            String d = this.tablaPiezas.getValueAt(rowSeleccionada, 3).toString();

            // actualizo la lista de piezas del table model y po lo tanto la fila en el Jtable
            this.tablaPiezas.getModel().setValueAt(cod, rowSeleccionada, 0);
            this.tablaPiezas.getModel().setValueAt(n, rowSeleccionada, 1);
            this.tablaPiezas.getModel().setValueAt(p, rowSeleccionada, 2);
            this.tablaPiezas.getModel().setValueAt(d, rowSeleccionada, 3);

            float price = Float.valueOf(p);

            Piezas nuevaPieza = new Piezas(cod,n,price,d);

            //actualizo la pieza en la bd
            nuevaPieza.modificarPieza(nuevaPieza);

        }else{

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA ");
        }
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void nuevaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaButtonActionPerformed
        // TODO add your handling code here:


        String code = textFieldCodigoPieza.getText();
        String name = textFieldNombre.getText();
        String price = textFieldPrecio.getText();
        String description = textFieldDescripcion.getText();

        float p = Float.valueOf(price);

        Piezas nuevaPieza = new Piezas(code,name,p,description);

        if(code.equalsIgnoreCase("")||name.equals("")
                ||price.equals("")||description.equals("") ){

            JOptionPane.showMessageDialog(null, "Introduzca todos los campos");

        }else if ( nuevaPieza.insertarPieza(nuevaPieza)){

             

            // inserto en la jtable
           this.modeloTablaPiezas.adicionarPieza(nuevaPieza);

           JOptionPane.showMessageDialog(null, "PIEZA INGRESADA CORRECTAMENTE");

        }

        // limpio los textfields
            limpiarTextfieldsPiezas();

           
    }//GEN-LAST:event_nuevaButtonActionPerformed

    private void buttonNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoProveedorActionPerformed
        // TODO add your handling code here:

        String code = textFieldCodigoProveedor.getText();
        String name = textFieldNombreProveedor.getText();
        String a = textFieldApellidos.getText();
        String d = textFieldDireccion.getText();

        Proveedores nuevoProveedor = new Proveedores(code,name,a,d);

        if(code.equalsIgnoreCase("")||name.equals("")
                ||a.equals("")||d.equals("") ){

            JOptionPane.showMessageDialog(null, "Introduzca todos los campos");

        }else if(// inserto el nuevo prov en la bd
            nuevoProveedor.insertarProveedor(nuevoProveedor)){
            
            JOptionPane.showMessageDialog(null, "PROVEEDOR GUARDADO EN BD CORRECTAMENTE");
             
            // inserto en la jtable
           this.modeloTablaProveedores.adicionarProveedor(nuevoProveedor);
                      
        }

        // limpio los textfields
            limpiarTextFieldsProveedores();


    }//GEN-LAST:event_buttonNuevoProveedorActionPerformed

    private void buttonEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarProveedorActionPerformed
        // TODO add your handling code here:

        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaProveedores.getSelectedRow();

        // compruebo que el usuario haya elegido alguna fila
        if (rowSeleccionada == -1) {

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA");

        } else {

            // obtengo los datos de la fila
            String cod = this.tablaProveedores.getModel().getValueAt(rowSeleccionada, 0).toString();
            String n = this.tablaProveedores.getModel().getValueAt(rowSeleccionada, 1).toString();
            String ap = this.tablaProveedores.getModel().getValueAt(rowSeleccionada, 2).toString();
            String dir = this.tablaProveedores.getModel().getValueAt(rowSeleccionada, 3).toString();

            // elimino del modelo la row
            this.modeloTablaProveedores.eliminarProveedor(rowSeleccionada);

            // creo el objeto
            Proveedores proveedor = new Proveedores(cod, n, ap, dir);

            // borro de la bd el proveedor
            proveedor.borrarProveedor(proveedor);

        }

    }//GEN-LAST:event_buttonEliminarProveedorActionPerformed

    private void buttonActualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarProveedorActionPerformed
        // TODO add your handling code here:

        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaProveedores.getSelectedRow();

        // compruebo que una celda esté seleccionada
        if(rowSeleccionada>=0){

            //obtengo los valores de la fila que se está editando
            String cod = this.tablaProveedores.getValueAt(rowSeleccionada, 0).toString();
            String name = this.tablaProveedores.getValueAt(rowSeleccionada, 1).toString();
            String apell = this.tablaProveedores.getValueAt(rowSeleccionada, 2).toString();
            String direc = this.tablaProveedores.getValueAt(rowSeleccionada, 3).toString();

            // actualizo la lista de proveedores del table model y por lo tanto la fila en el Jtable
            this.tablaProveedores.getModel().setValueAt(cod, rowSeleccionada, 0);
            this.tablaProveedores.getModel().setValueAt(name, rowSeleccionada, 1);
            this.tablaProveedores.getModel().setValueAt(apell, rowSeleccionada, 2);
            this.tablaProveedores.getModel().setValueAt(direc, rowSeleccionada, 3);

            Proveedores p = new Proveedores(cod,name,apell,direc);

            //actualizo el prov en la bd
            p.modificarProveedor(p);

        }else{

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA ");
        }
    }//GEN-LAST:event_buttonActualizarProveedorActionPerformed

    private void buttonNuevaReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevaReparacionActionPerformed
        // TODO add your handling code here:
        
        String code = textFieldCodigoReparacion.getText();
        String name = textFieldNombreReparacion.getText();
        String city = textFieldCiudadReparacion.getText();


        Reparaciones nuevaReparacion = new Reparaciones(code, name, city);

        if (code.equalsIgnoreCase("") || name.equals("")
                || city.equals("")) {

            JOptionPane.showMessageDialog(null, "Introduzca todos los campos");

        } else if (// inserto la nueva rep en la bd
                nuevaReparacion.insertarReparacion(nuevaReparacion)) {

            JOptionPane.showMessageDialog(null, "REPARACIÓN GUARDADA EN BD CORRECTAMENTE");

            // inserto en la jtable
            this.modeloTablaReparaciones.adicionarReparacion(nuevaReparacion);

        }

        // limpio los textfields
        limpiarTextFieldsReparaciones();



    }//GEN-LAST:event_buttonNuevaReparacionActionPerformed

    private void buttonEliminarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarReparacionActionPerformed
        // TODO add your handling code here:
        
        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaReparaciones.getSelectedRow();

        // compruebo que el usuario haya elegido alguna fila
        if (rowSeleccionada == -1) {

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA");

        } else {

            // obtengo los datos de la fila
            String cod = this.tablaReparaciones.getModel().getValueAt(rowSeleccionada, 0).toString();
            String n = this.tablaReparaciones.getModel().getValueAt(rowSeleccionada, 1).toString();
            String ap = this.tablaReparaciones.getModel().getValueAt(rowSeleccionada, 2).toString();
           

            // elimino del modelo la row
            this.modeloTablaReparaciones.eliminarReparacion(rowSeleccionada);

            // creo el objeto
            Reparaciones rep = new Reparaciones(cod, n, ap);

            // borro de la bd el proveedor
            rep.borrarReparacion(rep);
        }

    }//GEN-LAST:event_buttonEliminarReparacionActionPerformed

    private void buttonActualizarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarReparacionActionPerformed
        // TODO add your handling code here:
        
        //obtengo la fila seleccionada
        int rowSeleccionada = this.tablaReparaciones.getSelectedRow();

        // compruebo que una celda esté seleccionada
        if(rowSeleccionada>=0){

            //obtengo los valores de la fila que se está editando
            String cod = this.tablaReparaciones.getValueAt(rowSeleccionada, 0).toString();
            String name = this.tablaReparaciones.getValueAt(rowSeleccionada, 1).toString();
            String apell = this.tablaReparaciones.getValueAt(rowSeleccionada, 2).toString();
           

            // actualizo la lista de proveedores del table model y por lo tanto la fila en el Jtable
            this.tablaReparaciones.getModel().setValueAt(cod, rowSeleccionada, 0);
            this.tablaReparaciones.getModel().setValueAt(name, rowSeleccionada, 1);
            this.tablaReparaciones.getModel().setValueAt(apell, rowSeleccionada, 2);
            

            Reparaciones p = new Reparaciones(cod,name,apell);

            //actualizo la rep en la bd
            p.modificarReparacion(p);

        }else{

            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA ");
        }


    }//GEN-LAST:event_buttonActualizarReparacionActionPerformed

    private void jButtonBusqAvanzreparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusqAvanzreparacionesActionPerformed
        // TODO add your handling code here:
        
        String ciudad = jRadioButtonCiudadReparacion.getText();
        String nombre = jRadioButtonNombreReparacion.getText();
        String code = jRadioButtonCodigoReparacion.getText();
        
        String datoText = textFieldBusqAvanzReparaciones.getText().trim();

        ArrayList arrayListReparaciones = new ArrayList();
        Reparaciones reparacion = new Reparaciones();


        if(jRadioButtonCiudadReparacion.isSelected() && !textFieldBusqAvanzReparaciones.getText().equalsIgnoreCase("")){

           
            arrayListReparaciones = reparacion.listarReparacionesPorCampo(datoText, ciudad);

        }else if(jRadioButtonCodigoReparacion.isSelected()&& !textFieldBusqAvanzReparaciones.getText().equalsIgnoreCase("")){

           
            arrayListReparaciones = reparacion.listarReparacionesPorCampo(datoText, code);

        }else if (jRadioButtonListarReparaciones.isSelected()&& !textFieldBusqAvanzReparaciones.getText().equalsIgnoreCase("")){
           

            arrayListReparaciones = reparacion.listarReparaciones();

        }else if (jRadioButtonNombreReparacion.isSelected()&& !textFieldBusqAvanzReparaciones.getText().equalsIgnoreCase("")){
            
            arrayListReparaciones = reparacion.listarReparacionesPorCampo(datoText, nombre);

           

        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una opción e introduzca dato a buscar");

        }


        this.modeloTablaReparaciones = new ModeloTablaReparaciones(arrayListReparaciones);
        this.tablaReparaciones.setModel(this.modeloTablaReparaciones);


    }//GEN-LAST:event_jButtonBusqAvanzreparacionesActionPerformed

    private void buttonBusqAvanzProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBusqAvanzProveedoresActionPerformed
        // TODO add your handling code here:


        String ciudad = jRadioButtonDireccionProveedores.getText();
        String nombre = jRadioButtonNombreProveedores.getText();
        String code = jRadioButtonCodigoProveedores.getText();

        String datoText = textFieldBusqAvanProveedores.getText().trim();

        ArrayList arrayListProveedores = new ArrayList();
        Proveedores proveedor = new Proveedores();


        

        if(jRadioButtonCodigoProveedores.isSelected() && !textFieldBusqAvanProveedores.getText().equalsIgnoreCase("")){

            arrayListProveedores = proveedor.listarProveedoresPorCampo(datoText, code);

        }else if(jRadioButtonNombreProveedores.isSelected()&& !textFieldBusqAvanProveedores.getText().equalsIgnoreCase("")){

            arrayListProveedores = proveedor.listarProveedoresPorCampo(datoText, nombre);

        }else if (jRadioButtonDireccionProveedores.isSelected()&& !textFieldBusqAvanProveedores.getText().equalsIgnoreCase("")){

            arrayListProveedores = proveedor.listarProveedoresPorCampo(datoText, ciudad);

        }else if (jRadioButtonListarProveedores.isSelected()){

            arrayListProveedores = proveedor.listarProveedores();



        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una opción e introduzca dato a buscar");

        }


        this.modeloTablaProveedores = new ModeloTablaProveedores(arrayListProveedores);
        this.tablaProveedores.setModel(this.modeloTablaProveedores);
    }//GEN-LAST:event_buttonBusqAvanzProveedoresActionPerformed

    private void buttonBusqAvanzPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBusqAvanzPiezasActionPerformed
        // TODO add your handling code here:

        String code = jRadioButtonPiezasCodigo.getText();
        String nombre = jRadioButtonPiezasNombre.getText();
        
        String datoText = textFieldBusquAvanzPiezas.getText().trim();

        ArrayList arrayListPiezas = new ArrayList();
        Piezas pieza = new Piezas();

        if(jRadioButtonPiezasCodigo.isSelected() && !textFieldBusquAvanzPiezas.getText().equalsIgnoreCase("")){

            arrayListPiezas = pieza.listarPiezasPorCampo(datoText, code);

        }else if(jRadioButtonPiezasNombre.isSelected()&& !textFieldBusquAvanzPiezas.getText().equalsIgnoreCase("")){

            arrayListPiezas = pieza.listarPiezasPorCampo(datoText, nombre);

        }else if (jRadioButtonTodasLasPiezas.isSelected()){

             arrayListPiezas = pieza.listarPiezas();

        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una opción e introduzca dato a buscar");

        }

        this.modeloTablaPiezas = new ModeloTablaPiezas(arrayListPiezas);
        this.tablaPiezas.setModel(this.modeloTablaPiezas);

    }//GEN-LAST:event_buttonBusqAvanzPiezasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton buttonActualizarProveedor;
    private javax.swing.JButton buttonActualizarReparacion;
    private javax.swing.JButton buttonBusqAvanzPiezas;
    private javax.swing.JButton buttonBusqAvanzProveedores;
    private javax.swing.JButton buttonEliminarProveedor;
    private javax.swing.JButton buttonEliminarReparacion;
    private javax.swing.JButton buttonNuevaReparacion;
    private javax.swing.JButton buttonNuevoProveedor;
    private javax.swing.JPanel contenedorBusquedaAvGestiones;
    private javax.swing.JPanel contenedorBusquedaAvProveedores;
    private javax.swing.JPanel contenedorGestionProveedores;
    private javax.swing.JPanel contenedorGestionReparaciones;
    private javax.swing.JPanel contenedorPiezas;
    private javax.swing.JPanel contenedorPiezasBusquedaAvan;
    private javax.swing.JPanel contenedorPiezasControl;
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JPanel contenedorProveedores;
    private javax.swing.JPanel contenedorReparaciones;
    private javax.swing.JPanel contenedorTablaProveedores;
    private javax.swing.JPanel contenedorTablaProveedores1;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton jButtonBusqAvanzreparaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonCiudadReparacion;
    private javax.swing.JRadioButton jRadioButtonCodigoProveedores;
    private javax.swing.JRadioButton jRadioButtonCodigoReparacion;
    private javax.swing.JRadioButton jRadioButtonDireccionProveedores;
    private javax.swing.JRadioButton jRadioButtonListarProveedores;
    private javax.swing.JRadioButton jRadioButtonListarReparaciones;
    private javax.swing.JRadioButton jRadioButtonNombreProveedores;
    private javax.swing.JRadioButton jRadioButtonNombreReparacion;
    private javax.swing.JRadioButton jRadioButtonPiezasCodigo;
    private javax.swing.JRadioButton jRadioButtonPiezasNombre;
    private javax.swing.JRadioButton jRadioButtonTodasLasPiezas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton nuevaButton;
    private javax.swing.JTable tablaPiezas;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tablaReparaciones;
    private javax.swing.JTextField textFieldApellidos;
    private javax.swing.JTextField textFieldBusqAvanProveedores;
    private javax.swing.JTextField textFieldBusqAvanzReparaciones;
    private javax.swing.JTextField textFieldBusquAvanzPiezas;
    private javax.swing.JTextField textFieldCiudadReparacion;
    private javax.swing.JTextField textFieldCodigoPieza;
    private javax.swing.JTextField textFieldCodigoProveedor;
    private javax.swing.JTextField textFieldCodigoReparacion;
    private javax.swing.JTextField textFieldDescripcion;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNombreProveedor;
    private javax.swing.JTextField textFieldNombreReparacion;
    private javax.swing.JTextField textFieldPrecio;
    // End of variables declaration//GEN-END:variables

    // Table models
    private ModeloTablaPiezas modeloTablaPiezas;
    private ModeloTablaProveedores modeloTablaProveedores;
    private ModeloTablaReparaciones modeloTablaReparaciones;

     // metod to clean textFields
    public void limpiarTextfieldsPiezas(){

         textFieldCodigoPieza.setText("");
         textFieldNombre.setText("");
         textFieldPrecio.setText("");
         textFieldDescripcion.setText("");


    }

    // metod to clean proveedores TextFields
    public void limpiarTextFieldsProveedores(){
         textFieldCodigoProveedor.setText("");
         textFieldNombreProveedor.setText("");
         textFieldApellidos.setText("");
         textFieldDireccion.setText("");
    }

    // metod to clean reparaciones TextFields
    public void limpiarTextFieldsReparaciones(){
        textFieldCodigoReparacion.setText("");
        textFieldNombreReparacion.setText("");
        textFieldCiudadReparacion.setText("");
    }
    
}
